name: Tests

on: [ push, pull_request ]

jobs:
  test:
    name: test ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.11"
          - "3.10"
        os:
          - ubuntu-latest
    steps:
      - name: Setup python for tox
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install self-tox
        run: python -m pip install .
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - name: Setup test suite
        run: tox r -e py${{ matrix.py }} -vv --notest
      - name: Run test suite
        run: tox r -e py${{ matrix.py }} --skip-pkg-install
        env:
          CI_RUN: "yes"
          DIFF_AGAINST: HEAD
          PYTEST_XDIST_AUTO_NUM_WORKERS: 0

  check:
    name: tox env ${{ matrix.tox_env }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        tox_env:
          - lint
          - type
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install self-tox
        run: python -m pip install .
      - name: Run check for ${{ matrix.tox_env }}
        run: tox r -e ${{ matrix.tox_env }}
  